In [1]:
!ls data

Advertising.csv carseats.csv    hitters.csv     nci60_data.csv  usarrests.csv
Credit.csv      college.csv     khan_xtest.csv  nci60_labs.csv  wage.csv
auto.csv        default.csv     khan_xtrain.csv portfolio.csv   weekly.csv
boston.csv      employees.csv   khan_ytest.csv  smarket.csv
caravan.csv     employees2.csv  khan_ytrain.csv titanic.csv


In [37]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, KFold
import pandas as pd
import statsmodels.formula.api as smf
from sklearn.datasets import load_digits


digits = load_digits()

### Using the Default dataset

Preprocess the `default` dataset

Separate the X and y for `sklearn`, using `income` and `balance` for now

Use `sklearn` to fit a logistic regression model using only the training set and print the parameters (*hint*: use C=100000, tol=.0000001 values will help you create a decent model)

Use `statsmodels` to fit a logistic regression model

Print the summary report

Get the error rate for the `sklearn` model without validation set. *Hint*: the `predict` method will be helpful 

Get the error rate for the `statsmodel` model without validation set. *Hint*: the `predict` method will be helpful 

Create a new Logistic Regression model using the train-test split approach using both `sklearn` and `statsmodel`

Join the X and y columns so that we have a complete dataset for `statsmodel`

Fit a logistic regression model using `statsmodel` and print the results

Get the error rates for the `sklearn` and `statsmodel` models using the test set and compare the errors with the above models fitted without a validation set. *Hint*: the `predict` method will be helpful. 

In [ ]:
((results.predict(X) > .5) * 1 == y).mean(), (lr.predict(X) == y).mean()

Validation error of only .022

Use a for loop to repeat the above process for 3 different train/test splits

In [ ]:
for i in range(3):
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    lr = LogisticRegression(C=100000, tol=.0000001)
    lr.fit(X_train, y_train)
    # print(lr.score(X_test, y_test))
    
    X_train_sm = X_train.join(y_train)
    result = smf.logit('default_yes ~ income + balance', data=X_train_sm).fit()
    print(((result.predict(X) > .5) * 1 == y).mean(), (lr.predict(X) == y).mean())

Repeat the above step with student included in the model


In [ ]:
for i in range(3):
    X_train, X_test, y_train, y_test = train_test_split(X, y) ## x set needs to change dependant on independant variables, we're adding student_yes here so it needs to be added to x as well
    lr = LogisticRegression(C=100000, tol=.0000001)
    lr.fit(X_train, y_train)
    # print(lr.score(X_test, y_test))
    
    X_train_sm = X_train.join(y_train)
    result = smf.logit('default_yes ~ income + balance + student_yes', data=X_train_sm).fit()
    print(((result.predict(X) > .5) * 1 == y).mean(), (lr.predict(X) == y).mean())

The error rates should be very similar

### Use the [digits](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html) dataset from sklearn

CROSS VALIDATION!!

Split the digits into train and test sets. *Hint*: the features are stored in digits.data and the target values are in digits.target

In [38]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)
X_train.shape
y_train.shape

(1257,)

Fit a logistic regression model using the train/test split in the previous step

In [39]:
lr = LogisticRegression(C=100000, tol=.0000001)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.9481481481481482

For now, let's fit two more models using SVC and RandomForest

In [40]:
smv = SVC()
smv.fit(X_train, y_train)
smv.score(X_test, y_test)

# measure accuracy and area under the ROC curve
# precision as well
# recaulc?

C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.5018518518518519

In [41]:
rf = RandomForestClassifier(n_estimators =40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9722222222222222

Use k-fold cross validation with [`KFold`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html)

In [42]:
kf = KFold(n_splits=3)

For starters, pass in a small, random dataframe and observe what sets are produced from KFold

In [43]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Create a method that generalizes the model creation process (*hint*: your method should have 5 parameters)

In [44]:
# model is whichevber model you are using
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

Test our method

In [45]:
get_score(SVC(), X_train, X_test, y_train, y_test)

C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.5018518518518519

Compare the 3 models using k-fold CV

Shortcut: `cross_val_score` from `model_selection` will do exactly what we did in the above cell!

In [46]:
from sklearn.model_selection import cross_val_score

In [50]:
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=3)


C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\jkom8\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default so

array([0.89534884, 0.94991653, 0.90939597])

In [ ]:
## three different Logistic Regression scores for 3 folds.
## change values in the parameter of the models to try to get better model